# Generated by Django 6.0.6 on 2026-06-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pumbstatus',
            old_name='status',
            new_name='pumb_on',
        ),
    ]
